version: '3.8'

services:
  node1:
    image: redis:7.0.5
    container_name: redis-cluster-node-1
    volumes:
      - "./script/redisnode/redis.conf:/etc/redis.conf"
      - "./data/node1/data:/data"
    command: ["redis-server", "/etc/redis.conf"]
    restart: unless-stopped
    networks:
      - redis-cluster-network
    ports:
      - "6371:6379"

  node2:
    image: redis:7.0.5
    container_name: redis-cluster-node-2
    volumes:
      - "./script/redisnode/redis.conf:/etc/redis.conf"
      - "./data/node2/data:/data"
    command: ["redis-server", "/etc/redis.conf"]
    restart: unless-stopped
    networks:
      - redis-cluster-network
    ports:
      - "6372:6379"

  node3:
    image: redis:7.0.5
    container_name: redis-cluster-node-3
    volumes:
      - "./script/redisnode/redis.conf:/etc/redis.conf"
      - "./data/node3/data:/data"
    command: ["redis-server", "/etc/redis.conf"]
    restart: unless-stopped
    networks:
      - redis-cluster-network
    ports:
      - "6373:6379"
  node4:
    image: redis:7.0.5
    container_name: redis-cluster-node-4
    volumes:
      - "./script/redisnode/redis.conf:/etc/redis.conf"
      - "./data/node4/data:/data"
    command: [ "redis-server", "/etc/redis.conf" ]
    restart: unless-stopped
    networks:
      - redis-cluster-network
    ports:
      - "6374:6379"
  node5:
    image: redis:7.0.5
    container_name: redis-cluster-node-5
    volumes:
      - "./script/redisnode/redis.conf:/etc/redis.conf"
      - "./data/node5/data:/data"
    command: [ "redis-server", "/etc/redis.conf" ]
    restart: unless-stopped
    networks:
      - redis-cluster-network
    ports:
      - "6375:6379"
  node6:
    image: redis:7.0.5
    container_name: redis-cluster-node-6
    volumes:
      - "./script/redisnode/redis.conf:/etc/redis.conf"
      - "./data/node6/data:/data"
    command: [ "redis-server", "/etc/redis.conf" ]
    restart: unless-stopped
    networks:
      - redis-cluster-network
    ports:
      - "6376:6379"


networks:
  redis-cluster-network:
    driver: bridge

# redis-cli --cluster create 172.28.0.2:6379 172.28.0.4:6379 172.28.0.5:6379  172.28.0.7:6379 172.28.0.3:6379 172.28.0.6:6379   --cluster-replicas 1
