gen-rpc:
	 cd .\script\desc\rpc\ && goctl rpc protoc user.proto --go_out=../../../rpc/user --go-grpc_out=../../../rpc/user --zrpc_out=../../../rpc/user -m
	cd .\script\desc\rpc\ && goctl rpc protoc live.proto --go_out=../../../rpc/live --go-grpc_out=../../../rpc/live --zrpc_out=../../../rpc/live -m
run-env:
	docker-compose  -f docker-compose-env.yml up -d

gen-gin-api:
	gengin cctiktok.api

gen-i18n:
	goi18n extract -outdir ./pkg/lang
	cd ./pkg/lang &&  goi18n merge active.en.toml translate.zh.toml

gen-api:
	cd ./script/desc/api && goctl api go -api user.api -dir ../../../api/user --home ../../1.6.3
	cd ./script/desc/api && goctl api go -api live.api -dir ../../../api/live --home ../../1.6.3

gen-swagger:
	cd  ./script/desc/api && goctl api plugin -plugin goctl-swagger="swagger -filename user.json" -api user.api -dir ../../swagger
	cd  ./script/desc/api && goctl api plugin -plugin goctl-swagger="swagger -filename live.json" -api live.api -dir ../../swagger



ffmpeg:
	ffmpeg -f dshow  -i video="USB2.0 HD UVC WebCam":audio="Microphone (C-Media(R) Audio)" -vcodec h264 -acodec aac -f flv rtmp://localhost:1935/live/7/1726042205
	ffmpeg -re -i C:/Users/DENGFENGCHENG/Videos/Captures/mp4/time.mp4 -vcodec h264 -acodec aac -f flv rtmp://localhost:1935/live/6/1726042205