// Code generated by Kitex v0.9.1. DO NOT EDIT.

package userrpcservice

import (
	user "backend/app/rpc/user/kitex_gen/user"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"LoginWithUsername": kitex.NewMethodInfo(
		loginWithUsernameHandler,
		newLoginWithUsernameArgs,
		newLoginWithUsernameResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"LoginWithEmail": kitex.NewMethodInfo(
		loginWithEmailHandler,
		newLoginWithEmailArgs,
		newLoginWithEmailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"LoginWithPhone": kitex.NewMethodInfo(
		loginWithPhoneHandler,
		newLoginWithPhoneArgs,
		newLoginWithPhoneResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newRegisterArgs,
		newRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateUserInfo": kitex.NewMethodInfo(
		updateUserInfoHandler,
		newUpdateUserInfoArgs,
		newUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newLogoutArgs,
		newLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FollowerList": kitex.NewMethodInfo(
		followerListHandler,
		newFollowerListArgs,
		newFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FollowingList": kitex.NewMethodInfo(
		followingListHandler,
		newFollowingListArgs,
		newFollowingListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FriendList": kitex.NewMethodInfo(
		friendListHandler,
		newFriendListArgs,
		newFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newRefreshTokenArgs,
		newRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddFollowing": kitex.NewMethodInfo(
		addFollowingHandler,
		newAddFollowingArgs,
		newAddFollowingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddWhisper": kitex.NewMethodInfo(
		addWhisperHandler,
		newAddWhisperArgs,
		newAddWhisperResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddBlack": kitex.NewMethodInfo(
		addBlackHandler,
		newAddBlackArgs,
		newAddBlackResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DelFollowing": kitex.NewMethodInfo(
		delFollowingHandler,
		newDelFollowingArgs,
		newDelFollowingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DelWhisper": kitex.NewMethodInfo(
		delWhisperHandler,
		newDelWhisperArgs,
		newDelWhisperResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DelBlack": kitex.NewMethodInfo(
		delBlackHandler,
		newDelBlackArgs,
		newDelBlackResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserRelationship": kitex.NewMethodInfo(
		getUserRelationshipHandler,
		newGetUserRelationshipArgs,
		newGetUserRelationshipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	userRpcServiceServiceInfo                = NewServiceInfo()
	userRpcServiceServiceInfoForClient       = NewServiceInfoForClient()
	userRpcServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userRpcServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userRpcServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userRpcServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserRpcService"
	handlerType := (*user.UserRpcService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func loginWithUsernameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.LoginWithUsernameReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).LoginWithUsername(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LoginWithUsernameArgs:
		success, err := handler.(user.UserRpcService).LoginWithUsername(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginWithUsernameResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLoginWithUsernameArgs() interface{} {
	return &LoginWithUsernameArgs{}
}

func newLoginWithUsernameResult() interface{} {
	return &LoginWithUsernameResult{}
}

type LoginWithUsernameArgs struct {
	Req *user.LoginWithUsernameReq
}

func (p *LoginWithUsernameArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.LoginWithUsernameReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *LoginWithUsernameArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *LoginWithUsernameArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *LoginWithUsernameArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginWithUsernameArgs) Unmarshal(in []byte) error {
	msg := new(user.LoginWithUsernameReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginWithUsernameArgs_Req_DEFAULT *user.LoginWithUsernameReq

func (p *LoginWithUsernameArgs) GetReq() *user.LoginWithUsernameReq {
	if !p.IsSetReq() {
		return LoginWithUsernameArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginWithUsernameArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginWithUsernameArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginWithUsernameResult struct {
	Success *user.LoginResp
}

var LoginWithUsernameResult_Success_DEFAULT *user.LoginResp

func (p *LoginWithUsernameResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.LoginResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *LoginWithUsernameResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *LoginWithUsernameResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *LoginWithUsernameResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginWithUsernameResult) Unmarshal(in []byte) error {
	msg := new(user.LoginResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginWithUsernameResult) GetSuccess() *user.LoginResp {
	if !p.IsSetSuccess() {
		return LoginWithUsernameResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginWithUsernameResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LoginResp)
}

func (p *LoginWithUsernameResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginWithUsernameResult) GetResult() interface{} {
	return p.Success
}

func loginWithEmailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.LoginWithEmailReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).LoginWithEmail(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LoginWithEmailArgs:
		success, err := handler.(user.UserRpcService).LoginWithEmail(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginWithEmailResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLoginWithEmailArgs() interface{} {
	return &LoginWithEmailArgs{}
}

func newLoginWithEmailResult() interface{} {
	return &LoginWithEmailResult{}
}

type LoginWithEmailArgs struct {
	Req *user.LoginWithEmailReq
}

func (p *LoginWithEmailArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.LoginWithEmailReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *LoginWithEmailArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *LoginWithEmailArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *LoginWithEmailArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginWithEmailArgs) Unmarshal(in []byte) error {
	msg := new(user.LoginWithEmailReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginWithEmailArgs_Req_DEFAULT *user.LoginWithEmailReq

func (p *LoginWithEmailArgs) GetReq() *user.LoginWithEmailReq {
	if !p.IsSetReq() {
		return LoginWithEmailArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginWithEmailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginWithEmailArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginWithEmailResult struct {
	Success *user.LoginResp
}

var LoginWithEmailResult_Success_DEFAULT *user.LoginResp

func (p *LoginWithEmailResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.LoginResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *LoginWithEmailResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *LoginWithEmailResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *LoginWithEmailResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginWithEmailResult) Unmarshal(in []byte) error {
	msg := new(user.LoginResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginWithEmailResult) GetSuccess() *user.LoginResp {
	if !p.IsSetSuccess() {
		return LoginWithEmailResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginWithEmailResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LoginResp)
}

func (p *LoginWithEmailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginWithEmailResult) GetResult() interface{} {
	return p.Success
}

func loginWithPhoneHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.LoginWithPhoneReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).LoginWithPhone(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LoginWithPhoneArgs:
		success, err := handler.(user.UserRpcService).LoginWithPhone(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginWithPhoneResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLoginWithPhoneArgs() interface{} {
	return &LoginWithPhoneArgs{}
}

func newLoginWithPhoneResult() interface{} {
	return &LoginWithPhoneResult{}
}

type LoginWithPhoneArgs struct {
	Req *user.LoginWithPhoneReq
}

func (p *LoginWithPhoneArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.LoginWithPhoneReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *LoginWithPhoneArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *LoginWithPhoneArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *LoginWithPhoneArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginWithPhoneArgs) Unmarshal(in []byte) error {
	msg := new(user.LoginWithPhoneReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginWithPhoneArgs_Req_DEFAULT *user.LoginWithPhoneReq

func (p *LoginWithPhoneArgs) GetReq() *user.LoginWithPhoneReq {
	if !p.IsSetReq() {
		return LoginWithPhoneArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginWithPhoneArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginWithPhoneArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginWithPhoneResult struct {
	Success *user.LoginResp
}

var LoginWithPhoneResult_Success_DEFAULT *user.LoginResp

func (p *LoginWithPhoneResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.LoginResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *LoginWithPhoneResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *LoginWithPhoneResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *LoginWithPhoneResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginWithPhoneResult) Unmarshal(in []byte) error {
	msg := new(user.LoginResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginWithPhoneResult) GetSuccess() *user.LoginResp {
	if !p.IsSetSuccess() {
		return LoginWithPhoneResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginWithPhoneResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LoginResp)
}

func (p *LoginWithPhoneResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginWithPhoneResult) GetResult() interface{} {
	return p.Success
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.RegisterReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).Register(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RegisterArgs:
		success, err := handler.(user.UserRpcService).Register(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RegisterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRegisterArgs() interface{} {
	return &RegisterArgs{}
}

func newRegisterResult() interface{} {
	return &RegisterResult{}
}

type RegisterArgs struct {
	Req *user.RegisterReq
}

func (p *RegisterArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.RegisterReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *RegisterArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *RegisterArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *RegisterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RegisterArgs) Unmarshal(in []byte) error {
	msg := new(user.RegisterReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RegisterArgs_Req_DEFAULT *user.RegisterReq

func (p *RegisterArgs) GetReq() *user.RegisterReq {
	if !p.IsSetReq() {
		return RegisterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RegisterResult struct {
	Success *user.LoginResp
}

var RegisterResult_Success_DEFAULT *user.LoginResp

func (p *RegisterResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.LoginResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *RegisterResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *RegisterResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *RegisterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RegisterResult) Unmarshal(in []byte) error {
	msg := new(user.LoginResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RegisterResult) GetSuccess() *user.LoginResp {
	if !p.IsSetSuccess() {
		return RegisterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LoginResp)
}

func (p *RegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RegisterResult) GetResult() interface{} {
	return p.Success
}

func updateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.UpdateUserInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).UpdateUserInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateUserInfoArgs:
		success, err := handler.(user.UserRpcService).UpdateUserInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateUserInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateUserInfoArgs() interface{} {
	return &UpdateUserInfoArgs{}
}

func newUpdateUserInfoResult() interface{} {
	return &UpdateUserInfoResult{}
}

type UpdateUserInfoArgs struct {
	Req *user.UpdateUserInfoReq
}

func (p *UpdateUserInfoArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.UpdateUserInfoReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateUserInfoArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateUserInfoArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateUserInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateUserInfoArgs) Unmarshal(in []byte) error {
	msg := new(user.UpdateUserInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateUserInfoArgs_Req_DEFAULT *user.UpdateUserInfoReq

func (p *UpdateUserInfoArgs) GetReq() *user.UpdateUserInfoReq {
	if !p.IsSetReq() {
		return UpdateUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateUserInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateUserInfoResult struct {
	Success *user.UpdateUserInfoResp
}

var UpdateUserInfoResult_Success_DEFAULT *user.UpdateUserInfoResp

func (p *UpdateUserInfoResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.UpdateUserInfoResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateUserInfoResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateUserInfoResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateUserInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateUserInfoResult) Unmarshal(in []byte) error {
	msg := new(user.UpdateUserInfoResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateUserInfoResult) GetSuccess() *user.UpdateUserInfoResp {
	if !p.IsSetSuccess() {
		return UpdateUserInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.UpdateUserInfoResp)
}

func (p *UpdateUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateUserInfoResult) GetResult() interface{} {
	return p.Success
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.LogoutReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).Logout(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LogoutArgs:
		success, err := handler.(user.UserRpcService).Logout(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LogoutResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLogoutArgs() interface{} {
	return &LogoutArgs{}
}

func newLogoutResult() interface{} {
	return &LogoutResult{}
}

type LogoutArgs struct {
	Req *user.LogoutReq
}

func (p *LogoutArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.LogoutReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *LogoutArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *LogoutArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *LogoutArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LogoutArgs) Unmarshal(in []byte) error {
	msg := new(user.LogoutReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LogoutArgs_Req_DEFAULT *user.LogoutReq

func (p *LogoutArgs) GetReq() *user.LogoutReq {
	if !p.IsSetReq() {
		return LogoutArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LogoutArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LogoutResult struct {
	Success *user.LogoutResp
}

var LogoutResult_Success_DEFAULT *user.LogoutResp

func (p *LogoutResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.LogoutResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *LogoutResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *LogoutResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *LogoutResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LogoutResult) Unmarshal(in []byte) error {
	msg := new(user.LogoutResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LogoutResult) GetSuccess() *user.LogoutResp {
	if !p.IsSetSuccess() {
		return LogoutResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.LogoutResp)
}

func (p *LogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LogoutResult) GetResult() interface{} {
	return p.Success
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.FollowerListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).FollowerList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FollowerListArgs:
		success, err := handler.(user.UserRpcService).FollowerList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FollowerListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFollowerListArgs() interface{} {
	return &FollowerListArgs{}
}

func newFollowerListResult() interface{} {
	return &FollowerListResult{}
}

type FollowerListArgs struct {
	Req *user.FollowerListReq
}

func (p *FollowerListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.FollowerListReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *FollowerListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *FollowerListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *FollowerListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FollowerListArgs) Unmarshal(in []byte) error {
	msg := new(user.FollowerListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FollowerListArgs_Req_DEFAULT *user.FollowerListReq

func (p *FollowerListArgs) GetReq() *user.FollowerListReq {
	if !p.IsSetReq() {
		return FollowerListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FollowerListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FollowerListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FollowerListResult struct {
	Success *user.FollowerListResp
}

var FollowerListResult_Success_DEFAULT *user.FollowerListResp

func (p *FollowerListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.FollowerListResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *FollowerListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *FollowerListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *FollowerListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FollowerListResult) Unmarshal(in []byte) error {
	msg := new(user.FollowerListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FollowerListResult) GetSuccess() *user.FollowerListResp {
	if !p.IsSetSuccess() {
		return FollowerListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FollowerListResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.FollowerListResp)
}

func (p *FollowerListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FollowerListResult) GetResult() interface{} {
	return p.Success
}

func followingListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.FollowingListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).FollowingList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FollowingListArgs:
		success, err := handler.(user.UserRpcService).FollowingList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FollowingListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFollowingListArgs() interface{} {
	return &FollowingListArgs{}
}

func newFollowingListResult() interface{} {
	return &FollowingListResult{}
}

type FollowingListArgs struct {
	Req *user.FollowingListReq
}

func (p *FollowingListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.FollowingListReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *FollowingListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *FollowingListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *FollowingListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FollowingListArgs) Unmarshal(in []byte) error {
	msg := new(user.FollowingListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FollowingListArgs_Req_DEFAULT *user.FollowingListReq

func (p *FollowingListArgs) GetReq() *user.FollowingListReq {
	if !p.IsSetReq() {
		return FollowingListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FollowingListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FollowingListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FollowingListResult struct {
	Success *user.FollowingListResp
}

var FollowingListResult_Success_DEFAULT *user.FollowingListResp

func (p *FollowingListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.FollowingListResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *FollowingListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *FollowingListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *FollowingListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FollowingListResult) Unmarshal(in []byte) error {
	msg := new(user.FollowingListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FollowingListResult) GetSuccess() *user.FollowingListResp {
	if !p.IsSetSuccess() {
		return FollowingListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FollowingListResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.FollowingListResp)
}

func (p *FollowingListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FollowingListResult) GetResult() interface{} {
	return p.Success
}

func friendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.FriendListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).FriendList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FriendListArgs:
		success, err := handler.(user.UserRpcService).FriendList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FriendListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFriendListArgs() interface{} {
	return &FriendListArgs{}
}

func newFriendListResult() interface{} {
	return &FriendListResult{}
}

type FriendListArgs struct {
	Req *user.FriendListReq
}

func (p *FriendListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.FriendListReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *FriendListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *FriendListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *FriendListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FriendListArgs) Unmarshal(in []byte) error {
	msg := new(user.FriendListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FriendListArgs_Req_DEFAULT *user.FriendListReq

func (p *FriendListArgs) GetReq() *user.FriendListReq {
	if !p.IsSetReq() {
		return FriendListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FriendListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FriendListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FriendListResult struct {
	Success *user.FriendListResp
}

var FriendListResult_Success_DEFAULT *user.FriendListResp

func (p *FriendListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.FriendListResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *FriendListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *FriendListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *FriendListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FriendListResult) Unmarshal(in []byte) error {
	msg := new(user.FriendListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FriendListResult) GetSuccess() *user.FriendListResp {
	if !p.IsSetSuccess() {
		return FriendListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.FriendListResp)
}

func (p *FriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FriendListResult) GetResult() interface{} {
	return p.Success
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.RefreshTokenReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).RefreshToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RefreshTokenArgs:
		success, err := handler.(user.UserRpcService).RefreshToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RefreshTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRefreshTokenArgs() interface{} {
	return &RefreshTokenArgs{}
}

func newRefreshTokenResult() interface{} {
	return &RefreshTokenResult{}
}

type RefreshTokenArgs struct {
	Req *user.RefreshTokenReq
}

func (p *RefreshTokenArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.RefreshTokenReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *RefreshTokenArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *RefreshTokenArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *RefreshTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RefreshTokenArgs) Unmarshal(in []byte) error {
	msg := new(user.RefreshTokenReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RefreshTokenArgs_Req_DEFAULT *user.RefreshTokenReq

func (p *RefreshTokenArgs) GetReq() *user.RefreshTokenReq {
	if !p.IsSetReq() {
		return RefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefreshTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RefreshTokenResult struct {
	Success *user.RefreshTokenResp
}

var RefreshTokenResult_Success_DEFAULT *user.RefreshTokenResp

func (p *RefreshTokenResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.RefreshTokenResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *RefreshTokenResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *RefreshTokenResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *RefreshTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RefreshTokenResult) Unmarshal(in []byte) error {
	msg := new(user.RefreshTokenResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RefreshTokenResult) GetSuccess() *user.RefreshTokenResp {
	if !p.IsSetSuccess() {
		return RefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.RefreshTokenResp)
}

func (p *RefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefreshTokenResult) GetResult() interface{} {
	return p.Success
}

func addFollowingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.AddFollowingReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).AddFollowing(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddFollowingArgs:
		success, err := handler.(user.UserRpcService).AddFollowing(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddFollowingResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddFollowingArgs() interface{} {
	return &AddFollowingArgs{}
}

func newAddFollowingResult() interface{} {
	return &AddFollowingResult{}
}

type AddFollowingArgs struct {
	Req *user.AddFollowingReq
}

func (p *AddFollowingArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.AddFollowingReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddFollowingArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddFollowingArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddFollowingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddFollowingArgs) Unmarshal(in []byte) error {
	msg := new(user.AddFollowingReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddFollowingArgs_Req_DEFAULT *user.AddFollowingReq

func (p *AddFollowingArgs) GetReq() *user.AddFollowingReq {
	if !p.IsSetReq() {
		return AddFollowingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddFollowingArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddFollowingArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddFollowingResult struct {
	Success *user.AddFollowingResp
}

var AddFollowingResult_Success_DEFAULT *user.AddFollowingResp

func (p *AddFollowingResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.AddFollowingResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddFollowingResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddFollowingResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddFollowingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddFollowingResult) Unmarshal(in []byte) error {
	msg := new(user.AddFollowingResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddFollowingResult) GetSuccess() *user.AddFollowingResp {
	if !p.IsSetSuccess() {
		return AddFollowingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddFollowingResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.AddFollowingResp)
}

func (p *AddFollowingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddFollowingResult) GetResult() interface{} {
	return p.Success
}

func addWhisperHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.AddWhisperReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).AddWhisper(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddWhisperArgs:
		success, err := handler.(user.UserRpcService).AddWhisper(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddWhisperResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddWhisperArgs() interface{} {
	return &AddWhisperArgs{}
}

func newAddWhisperResult() interface{} {
	return &AddWhisperResult{}
}

type AddWhisperArgs struct {
	Req *user.AddWhisperReq
}

func (p *AddWhisperArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.AddWhisperReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddWhisperArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddWhisperArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddWhisperArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddWhisperArgs) Unmarshal(in []byte) error {
	msg := new(user.AddWhisperReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddWhisperArgs_Req_DEFAULT *user.AddWhisperReq

func (p *AddWhisperArgs) GetReq() *user.AddWhisperReq {
	if !p.IsSetReq() {
		return AddWhisperArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddWhisperArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddWhisperArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddWhisperResult struct {
	Success *user.AddWhisperResp
}

var AddWhisperResult_Success_DEFAULT *user.AddWhisperResp

func (p *AddWhisperResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.AddWhisperResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddWhisperResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddWhisperResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddWhisperResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddWhisperResult) Unmarshal(in []byte) error {
	msg := new(user.AddWhisperResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddWhisperResult) GetSuccess() *user.AddWhisperResp {
	if !p.IsSetSuccess() {
		return AddWhisperResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddWhisperResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.AddWhisperResp)
}

func (p *AddWhisperResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddWhisperResult) GetResult() interface{} {
	return p.Success
}

func addBlackHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.AddBlackReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).AddBlack(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddBlackArgs:
		success, err := handler.(user.UserRpcService).AddBlack(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddBlackResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddBlackArgs() interface{} {
	return &AddBlackArgs{}
}

func newAddBlackResult() interface{} {
	return &AddBlackResult{}
}

type AddBlackArgs struct {
	Req *user.AddBlackReq
}

func (p *AddBlackArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.AddBlackReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddBlackArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddBlackArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddBlackArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddBlackArgs) Unmarshal(in []byte) error {
	msg := new(user.AddBlackReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddBlackArgs_Req_DEFAULT *user.AddBlackReq

func (p *AddBlackArgs) GetReq() *user.AddBlackReq {
	if !p.IsSetReq() {
		return AddBlackArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddBlackArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddBlackArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddBlackResult struct {
	Success *user.AddBlackResp
}

var AddBlackResult_Success_DEFAULT *user.AddBlackResp

func (p *AddBlackResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.AddBlackResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddBlackResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddBlackResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddBlackResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddBlackResult) Unmarshal(in []byte) error {
	msg := new(user.AddBlackResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddBlackResult) GetSuccess() *user.AddBlackResp {
	if !p.IsSetSuccess() {
		return AddBlackResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddBlackResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.AddBlackResp)
}

func (p *AddBlackResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddBlackResult) GetResult() interface{} {
	return p.Success
}

func delFollowingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.DelFollowingReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).DelFollowing(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DelFollowingArgs:
		success, err := handler.(user.UserRpcService).DelFollowing(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DelFollowingResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDelFollowingArgs() interface{} {
	return &DelFollowingArgs{}
}

func newDelFollowingResult() interface{} {
	return &DelFollowingResult{}
}

type DelFollowingArgs struct {
	Req *user.DelFollowingReq
}

func (p *DelFollowingArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.DelFollowingReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DelFollowingArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DelFollowingArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DelFollowingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DelFollowingArgs) Unmarshal(in []byte) error {
	msg := new(user.DelFollowingReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DelFollowingArgs_Req_DEFAULT *user.DelFollowingReq

func (p *DelFollowingArgs) GetReq() *user.DelFollowingReq {
	if !p.IsSetReq() {
		return DelFollowingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DelFollowingArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DelFollowingArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DelFollowingResult struct {
	Success *user.DelFollowingResp
}

var DelFollowingResult_Success_DEFAULT *user.DelFollowingResp

func (p *DelFollowingResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.DelFollowingResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DelFollowingResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DelFollowingResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DelFollowingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DelFollowingResult) Unmarshal(in []byte) error {
	msg := new(user.DelFollowingResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DelFollowingResult) GetSuccess() *user.DelFollowingResp {
	if !p.IsSetSuccess() {
		return DelFollowingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DelFollowingResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.DelFollowingResp)
}

func (p *DelFollowingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DelFollowingResult) GetResult() interface{} {
	return p.Success
}

func delWhisperHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.DelWhisperReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).DelWhisper(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DelWhisperArgs:
		success, err := handler.(user.UserRpcService).DelWhisper(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DelWhisperResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDelWhisperArgs() interface{} {
	return &DelWhisperArgs{}
}

func newDelWhisperResult() interface{} {
	return &DelWhisperResult{}
}

type DelWhisperArgs struct {
	Req *user.DelWhisperReq
}

func (p *DelWhisperArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.DelWhisperReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DelWhisperArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DelWhisperArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DelWhisperArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DelWhisperArgs) Unmarshal(in []byte) error {
	msg := new(user.DelWhisperReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DelWhisperArgs_Req_DEFAULT *user.DelWhisperReq

func (p *DelWhisperArgs) GetReq() *user.DelWhisperReq {
	if !p.IsSetReq() {
		return DelWhisperArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DelWhisperArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DelWhisperArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DelWhisperResult struct {
	Success *user.DelWhisperResp
}

var DelWhisperResult_Success_DEFAULT *user.DelWhisperResp

func (p *DelWhisperResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.DelWhisperResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DelWhisperResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DelWhisperResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DelWhisperResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DelWhisperResult) Unmarshal(in []byte) error {
	msg := new(user.DelWhisperResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DelWhisperResult) GetSuccess() *user.DelWhisperResp {
	if !p.IsSetSuccess() {
		return DelWhisperResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DelWhisperResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.DelWhisperResp)
}

func (p *DelWhisperResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DelWhisperResult) GetResult() interface{} {
	return p.Success
}

func delBlackHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.DelBlackReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).DelBlack(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DelBlackArgs:
		success, err := handler.(user.UserRpcService).DelBlack(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DelBlackResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDelBlackArgs() interface{} {
	return &DelBlackArgs{}
}

func newDelBlackResult() interface{} {
	return &DelBlackResult{}
}

type DelBlackArgs struct {
	Req *user.DelBlackReq
}

func (p *DelBlackArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.DelBlackReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DelBlackArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DelBlackArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DelBlackArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DelBlackArgs) Unmarshal(in []byte) error {
	msg := new(user.DelBlackReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DelBlackArgs_Req_DEFAULT *user.DelBlackReq

func (p *DelBlackArgs) GetReq() *user.DelBlackReq {
	if !p.IsSetReq() {
		return DelBlackArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DelBlackArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DelBlackArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DelBlackResult struct {
	Success *user.DelBlackResp
}

var DelBlackResult_Success_DEFAULT *user.DelBlackResp

func (p *DelBlackResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.DelBlackResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DelBlackResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DelBlackResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DelBlackResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DelBlackResult) Unmarshal(in []byte) error {
	msg := new(user.DelBlackResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DelBlackResult) GetSuccess() *user.DelBlackResp {
	if !p.IsSetSuccess() {
		return DelBlackResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DelBlackResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.DelBlackResp)
}

func (p *DelBlackResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DelBlackResult) GetResult() interface{} {
	return p.Success
}

func getUserRelationshipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.GetUserRelationshipReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.UserRpcService).GetUserRelationship(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserRelationshipArgs:
		success, err := handler.(user.UserRpcService).GetUserRelationship(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserRelationshipResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserRelationshipArgs() interface{} {
	return &GetUserRelationshipArgs{}
}

func newGetUserRelationshipResult() interface{} {
	return &GetUserRelationshipResult{}
}

type GetUserRelationshipArgs struct {
	Req *user.GetUserRelationshipReq
}

func (p *GetUserRelationshipArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.GetUserRelationshipReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetUserRelationshipArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetUserRelationshipArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetUserRelationshipArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserRelationshipArgs) Unmarshal(in []byte) error {
	msg := new(user.GetUserRelationshipReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserRelationshipArgs_Req_DEFAULT *user.GetUserRelationshipReq

func (p *GetUserRelationshipArgs) GetReq() *user.GetUserRelationshipReq {
	if !p.IsSetReq() {
		return GetUserRelationshipArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserRelationshipArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserRelationshipArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserRelationshipResult struct {
	Success *user.GetUserRelationshipResp
}

var GetUserRelationshipResult_Success_DEFAULT *user.GetUserRelationshipResp

func (p *GetUserRelationshipResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.GetUserRelationshipResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetUserRelationshipResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetUserRelationshipResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetUserRelationshipResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserRelationshipResult) Unmarshal(in []byte) error {
	msg := new(user.GetUserRelationshipResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserRelationshipResult) GetSuccess() *user.GetUserRelationshipResp {
	if !p.IsSetSuccess() {
		return GetUserRelationshipResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserRelationshipResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.GetUserRelationshipResp)
}

func (p *GetUserRelationshipResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserRelationshipResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) LoginWithUsername(ctx context.Context, Req *user.LoginWithUsernameReq) (r *user.LoginResp, err error) {
	var _args LoginWithUsernameArgs
	_args.Req = Req
	var _result LoginWithUsernameResult
	if err = p.c.Call(ctx, "LoginWithUsername", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginWithEmail(ctx context.Context, Req *user.LoginWithEmailReq) (r *user.LoginResp, err error) {
	var _args LoginWithEmailArgs
	_args.Req = Req
	var _result LoginWithEmailResult
	if err = p.c.Call(ctx, "LoginWithEmail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginWithPhone(ctx context.Context, Req *user.LoginWithPhoneReq) (r *user.LoginResp, err error) {
	var _args LoginWithPhoneArgs
	_args.Req = Req
	var _result LoginWithPhoneResult
	if err = p.c.Call(ctx, "LoginWithPhone", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, Req *user.RegisterReq) (r *user.LoginResp, err error) {
	var _args RegisterArgs
	_args.Req = Req
	var _result RegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInfo(ctx context.Context, Req *user.UpdateUserInfoReq) (r *user.UpdateUserInfoResp, err error) {
	var _args UpdateUserInfoArgs
	_args.Req = Req
	var _result UpdateUserInfoResult
	if err = p.c.Call(ctx, "UpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, Req *user.LogoutReq) (r *user.LogoutResp, err error) {
	var _args LogoutArgs
	_args.Req = Req
	var _result LogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, Req *user.FollowerListReq) (r *user.FollowerListResp, err error) {
	var _args FollowerListArgs
	_args.Req = Req
	var _result FollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowingList(ctx context.Context, Req *user.FollowingListReq) (r *user.FollowingListResp, err error) {
	var _args FollowingListArgs
	_args.Req = Req
	var _result FollowingListResult
	if err = p.c.Call(ctx, "FollowingList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FriendList(ctx context.Context, Req *user.FriendListReq) (r *user.FriendListResp, err error) {
	var _args FriendListArgs
	_args.Req = Req
	var _result FriendListResult
	if err = p.c.Call(ctx, "FriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, Req *user.RefreshTokenReq) (r *user.RefreshTokenResp, err error) {
	var _args RefreshTokenArgs
	_args.Req = Req
	var _result RefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddFollowing(ctx context.Context, Req *user.AddFollowingReq) (r *user.AddFollowingResp, err error) {
	var _args AddFollowingArgs
	_args.Req = Req
	var _result AddFollowingResult
	if err = p.c.Call(ctx, "AddFollowing", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddWhisper(ctx context.Context, Req *user.AddWhisperReq) (r *user.AddWhisperResp, err error) {
	var _args AddWhisperArgs
	_args.Req = Req
	var _result AddWhisperResult
	if err = p.c.Call(ctx, "AddWhisper", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddBlack(ctx context.Context, Req *user.AddBlackReq) (r *user.AddBlackResp, err error) {
	var _args AddBlackArgs
	_args.Req = Req
	var _result AddBlackResult
	if err = p.c.Call(ctx, "AddBlack", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelFollowing(ctx context.Context, Req *user.DelFollowingReq) (r *user.DelFollowingResp, err error) {
	var _args DelFollowingArgs
	_args.Req = Req
	var _result DelFollowingResult
	if err = p.c.Call(ctx, "DelFollowing", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelWhisper(ctx context.Context, Req *user.DelWhisperReq) (r *user.DelWhisperResp, err error) {
	var _args DelWhisperArgs
	_args.Req = Req
	var _result DelWhisperResult
	if err = p.c.Call(ctx, "DelWhisper", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelBlack(ctx context.Context, Req *user.DelBlackReq) (r *user.DelBlackResp, err error) {
	var _args DelBlackArgs
	_args.Req = Req
	var _result DelBlackResult
	if err = p.c.Call(ctx, "DelBlack", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserRelationship(ctx context.Context, Req *user.GetUserRelationshipReq) (r *user.GetUserRelationshipResp, err error) {
	var _args GetUserRelationshipArgs
	_args.Req = Req
	var _result GetUserRelationshipResult
	if err = p.c.Call(ctx, "GetUserRelationship", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
