// Code generated by hertz generator.

package file

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newmultiuploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completemultipartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmultiuploaduriMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsuccesschunksMw() []app.HandlerFunc {
	// your code...
	return nil
}
