// Code generated by hertz generator.

package user

import (
	"backend/app/http/user/biz/dal"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginwithemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginwithphoneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginwithusernameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followinglistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _useruploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	apphandleFunc := make([]app.HandlerFunc, 0)
	apphandleFunc = append(apphandleFunc, dal.JWTMiddleware())
	return apphandleFunc
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
