// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userfollowrpcservice

import (
	"context"

	"backend/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FollowUserReq        = user.FollowUserReq
	FollowUserResp       = user.FollowUserResp
	FollowerListReq      = user.FollowerListReq
	FollowerListResp     = user.FollowerListResp
	FollowingListReq     = user.FollowingListReq
	FollowingListResp    = user.FollowingListResp
	FriendListReq        = user.FriendListReq
	FriendListResp       = user.FriendListResp
	Info                 = user.Info
	LoginResp            = user.LoginResp
	LoginWithEmailReq    = user.LoginWithEmailReq
	LoginWithPhoneReq    = user.LoginWithPhoneReq
	LoginWithUsernameReq = user.LoginWithUsernameReq
	LogoutReq            = user.LogoutReq
	LogoutResp           = user.LogoutResp
	RegisterReq          = user.RegisterReq
	UpdateUserInfoReq    = user.UpdateUserInfoReq
	UpdateUserInfoResp   = user.UpdateUserInfoResp
	User                 = user.User
	UserUploadFileReq    = user.UserUploadFileReq
	UserUploadFileResp   = user.UserUploadFileResp

	UserFollowRpcService interface {
		FollowUser(ctx context.Context, in *FollowUserReq, opts ...grpc.CallOption) (*FollowUserResp, error)
		FollowerList(ctx context.Context, in *FollowerListReq, opts ...grpc.CallOption) (*FollowerListResp, error)
		FollowingList(ctx context.Context, in *FollowingListReq, opts ...grpc.CallOption) (*FollowingListResp, error)
		FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)
	}

	defaultUserFollowRpcService struct {
		cli zrpc.Client
	}
)

func NewUserFollowRpcService(cli zrpc.Client) UserFollowRpcService {
	return &defaultUserFollowRpcService{
		cli: cli,
	}
}

func (m *defaultUserFollowRpcService) FollowUser(ctx context.Context, in *FollowUserReq, opts ...grpc.CallOption) (*FollowUserResp, error) {
	client := user.NewUserFollowRpcServiceClient(m.cli.Conn())
	return client.FollowUser(ctx, in, opts...)
}

func (m *defaultUserFollowRpcService) FollowerList(ctx context.Context, in *FollowerListReq, opts ...grpc.CallOption) (*FollowerListResp, error) {
	client := user.NewUserFollowRpcServiceClient(m.cli.Conn())
	return client.FollowerList(ctx, in, opts...)
}

func (m *defaultUserFollowRpcService) FollowingList(ctx context.Context, in *FollowingListReq, opts ...grpc.CallOption) (*FollowingListResp, error) {
	client := user.NewUserFollowRpcServiceClient(m.cli.Conn())
	return client.FollowingList(ctx, in, opts...)
}

func (m *defaultUserFollowRpcService) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	client := user.NewUserFollowRpcServiceClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}
