AuthorizationError = "Authorization error"
CommentNotExistError = "The comment is not exist"
EmailExistError = "The email is already in use"
FollowingIsExistError = "The following is exist"
FollowingIsNotExistError = "The following is not exist"
InvalidParamsError = "Invalid parameters {{.Params}}"
LiveIsOverError = "The live is over"
LiveLikeIsExistError = "The live like is exist"
LiveLikeNotExistError = "The live like is not exist"
LiveNotExistError = "The live is not exist"
Ok = "Success"
PassWordError = "The password is incorrect"
PhoneExistError = "The phone number is already in use"
ServerError = "Server error"
UserDisableError = "The user is disabled"
UserExistError = "The {{.UID}} is exist"
UserNotAllowLiveError = "The user is not allowed to live"
UserNotExistError = "The {{.UID}} is not exist"
UserPasswordError = "The password is incorrect"
UserRoleNotAllowError = "The user role right is not allowed"
UserUploadVideoError = "Error uploading the video"
