[AuthorizationError]
hash = "sha1-14a7e84261230bbb4b1ed8b2fc1a0afddf92688d"
other = "Authorization error"

[CommentNotExistError]
hash = "sha1-bbd143b4e3fea988ccff6e2c4bfcfdb6e0441a13"
other = "The comment is not exist"

[FollowingIsExistError]
hash = "sha1-7a70c0009aa3ee4bce408283a1e781e76c64910f"
other = "The following is exist"

[FollowingIsNotExistError]
hash = "sha1-21c8132b6c82574412b2b2fa3debc7867b2a14aa"
other = "The following is not exist"

[InvalidParamsError]
hash = "sha1-b9ceaa9a6b1899c76d8f8d19df755d91b4a751c3"
other = "Invalid parameters {{.Params}}"

[LiveIsOverError]
hash = "sha1-54ce414cee9ba71159e512af554f0ca304406ea9"
other = "The live is over"

[LiveLikeIsExistError]
hash = "sha1-5b317c7331b941f176a3b6d9abc92e2ea3610f09"
other = "The live like is exist"

[LiveLikeNotExistError]
hash = "sha1-833c89f1965e7e53708a09682515b306fe4ea012"
other = "The live like is not exist"

[LiveNotExistError]
hash = "sha1-9ac628454d3d8c153251f8bfabb490d28c5e7544"
other = "The live is not exist"

[Ok]
hash = "sha1-42a8f651d79fd005eeac0612df6442b983a01184"
other = "Success"

[ServerError]
hash = "sha1-82108cbfff92ae1bfbd851712f68ad73244f7468"
other = "Server error"

[UserNotAllowLiveError]
hash = "sha1-caf08d18374bd769a7050ec634af463c5cc5f686"
other = "The user is not allowed to live"

[UserRoleNotAllowError]
hash = "sha1-e70c2d0ccf5335c7fe1539383386f8636b7c0ca0"
other = "The user role right is not allowed"

[EmailExistError]
hash = "sha1-9582c9e117ff36d1f296a76d0e8dbab475448605"
other = "该邮箱已被使用"

[PassWordError]
hash = "sha1-a64daf893d1c3d1a06add30b308e8a2a7d42e7cf"
other = "密码错误"

[PhoneExistError]
hash = "sha1-abf5b4ccd2c6d9b70960192d866f93b146d1cc58"
other = "该手机号已被使用"

[UserDisableError]
hash = "sha1-3788827ac32af5c765df6c6f3465ecbdafc197b5"
other = "用户已被禁用"

[UserExistError]
hash = "sha1-894486e98fb1300cc5fe5a9b090c0770d0eb6ba9"
other = "用户 {{.UID}} 已存在"

[UserNotExistError]
hash = "sha1-113cc36f6a8630f17dfaab114d1ddbbf443103fe"
other = "用户 {{.UID}} 不存在"

[UserPasswordError]
hash = "sha1-a64daf893d1c3d1a06add30b308e8a2a7d42e7cf"
other = "密码错误"

[UserUploadVideoError]
hash = "sha1-c64d246657dea8da65d311212e00b4b884689748"
other = "上传视频出错"